// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwqnpmkrudfxfbpvsmzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3cW5wbWtydWRmeGZicHZzbXpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNDQwNzAsImV4cCI6MjA2ODYyMDA3MH0.zxQ4cVHFwpZaPIa_4n3AdU0sfoABLcRipJc_DW79ZBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});